# Frontend Dockerfile (multi-stage: build with Node, serve with nginx)
# TODO: FROM node:20-slim AS build
# TODO: WORKDIR /app; COPY package.json . && npm install; COPY . .; RUN npm run build
# TODO: FROM nginx:alpine
# TODO: COPY --from=build /app/dist /usr/share/nginx/html
# TODO: COPY nginx.conf /etc/nginx/conf.d/default.conf
# TODO: EXPOSE 80
