# Backend Dockerfile
# TODO: FROM python:3.11-slim
# TODO: WORKDIR /app
# TODO: COPY requirements.txt . && pip install -r requirements.txt
# TODO: COPY app ./app
# TODO: COPY db ./db
# TODO: EXPOSE 8000
# TODO: CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
